# Generated by Django 4.1 on 2022-09-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('hidden', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('finished', 'finished')], max_length=8)),
                ('due_date', models.DateTimeField()),
                ('hw_questions', models.JSONField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course_app.course')),
            ],
        ),
    ]
