# Generated by Django 4.1 on 2022-09-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('email_hash', models.CharField(max_length=40)),
                ('scores', models.JSONField()),
                ('total_score', models.IntegerField(blank=True, default=0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course')),
            ],
        ),
    ]
